// <auto-generated />
using System;
using CryptoBot.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CryptoBot.Data.Migrations
{
    [DbContext(typeof(CryptoBotDbContext))]
    [Migration("20240531215441_SetNullableSelectedAccount")]
    partial class SetNullableSelectedAccount
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CryptoBot.Data.Entities.AccountEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ChatId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ExchangeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ChatId");

                    b.HasIndex("ExchangeId")
                        .IsUnique();

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("CryptoBot.Data.Entities.ChatEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BotState")
                        .HasColumnType("int");

                    b.Property<long>("ChatId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("SelectedAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SelectedAccountId")
                        .IsUnique()
                        .HasFilter("[SelectedAccountId] IS NOT NULL");

                    b.ToTable("Chats");
                });

            modelBuilder.Entity("CryptoBot.Data.Entities.ExchangeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EncryptedKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EncryptedSecret")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Exchange")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Exchanges");
                });

            modelBuilder.Entity("CryptoBot.Data.Entities.AccountEntity", b =>
                {
                    b.HasOne("CryptoBot.Data.Entities.ChatEntity", "Chat")
                        .WithMany("Accounts")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CryptoBot.Data.Entities.ExchangeEntity", "Exchange")
                        .WithOne("Account")
                        .HasForeignKey("CryptoBot.Data.Entities.AccountEntity", "ExchangeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chat");

                    b.Navigation("Exchange");
                });

            modelBuilder.Entity("CryptoBot.Data.Entities.ChatEntity", b =>
                {
                    b.HasOne("CryptoBot.Data.Entities.AccountEntity", "SelectedAccount")
                        .WithOne()
                        .HasForeignKey("CryptoBot.Data.Entities.ChatEntity", "SelectedAccountId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("SelectedAccount");
                });

            modelBuilder.Entity("CryptoBot.Data.Entities.ChatEntity", b =>
                {
                    b.Navigation("Accounts");
                });

            modelBuilder.Entity("CryptoBot.Data.Entities.ExchangeEntity", b =>
                {
                    b.Navigation("Account");
                });
#pragma warning restore 612, 618
        }
    }
}
